name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Uses the latest version

      - name: Setup Node
        uses: actions/setup-node@v3  # Uses the latest version
        with:
          node-version: '20'  # Specify Node.js version 20

      - name: Check Node version  # Log the Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install  # Use npm install directly instead of the bahmutov action

      - name: Build project
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3  # Updated to latest version
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3  # Uses the latest version
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Uses the latest version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
